# SPDX-License-Identifier: Apache-2.0
"""Meridian V1 provider-neutral Streaming Catalog."""

from ._version import __version__
from .capabilities import (
    CAPABILITY_CONTRACT_VERSION,
    StreamingDescriptor,
    negotiate_streaming_capabilities,
    require_streaming_capabilities,
    streaming_requirements,
)
from .catalog import (
    STREAMING_CONTRACT_VERSION,
    STREAMING_REGISTRY_REF,
    StreamingCatalogProvider,
    StreamingCatalogSurface,
    streaming_manifest,
)
from .contracts import compatibility_contract, contract_document, public_api_contract
from .data import (
    CURSOR_FORMAT_VERSION,
    DELIVERY_FORMAT_VERSION,
    DELIVERY_TOKEN_FORMAT_VERSION,
    EVENT_FORMAT_VERSION,
    POSITION_FORMAT_VERSION,
    Cursor,
    Delivery,
    DeliveryToken,
    Event,
    Position,
    PublishReceipt,
    RangePage,
)
from .errors import (
    AcknowledgementConflict,
    CursorExpired,
    DeliveryRejected,
    DeliveryTimeout,
    GroupPositionConflict,
    InvalidCursor,
    InvalidEvent,
    InvalidStreamingDefinition,
    MigrationRequired,
    RebalanceConflict,
    RetentionBoundaryExceeded,
    StreamingCapabilityMismatch,
    StreamingPolicyDenied,
    StreamingResourceNotFound,
    StreamingUnavailable,
)
from .hooks import (
    EvidenceKind,
    StreamingEvidence,
    StreamingEvidenceHook,
    StreamingHooks,
    StreamingPolicyHook,
)
from .operations import (
    EXPLICIT_OPERATION_VERSION,
    GROUP_POSITION_OPERATION_CONTRACT,
    REPLAY_OPERATION_CONTRACT,
    GroupPositionTransition,
    ReplayOperation,
)
from .resources import (
    CATALOG_NAME,
    RESOURCE_FORMAT_VERSION,
    ConsumerGroup,
    DeliveryGuarantee,
    OrderingGuarantee,
    ResourceKind,
    ResourcePolicy,
    Stream,
    StreamingResource,
    Subscription,
    resource_from_mapping,
)
from .validation import (
    MAX_BATCH_SIZE,
    MAX_POLL_SIZE,
    MAX_RANGE_SIZE,
    MAX_WAIT_TIMEOUT_MS,
    parse_resource,
    validate_expression_arguments,
)

__all__ = [
    "CAPABILITY_CONTRACT_VERSION",
    "CATALOG_NAME",
    "CURSOR_FORMAT_VERSION",
    "DELIVERY_FORMAT_VERSION",
    "DELIVERY_TOKEN_FORMAT_VERSION",
    "EVENT_FORMAT_VERSION",
    "EXPLICIT_OPERATION_VERSION",
    "GROUP_POSITION_OPERATION_CONTRACT",
    "MAX_BATCH_SIZE",
    "MAX_POLL_SIZE",
    "MAX_RANGE_SIZE",
    "MAX_WAIT_TIMEOUT_MS",
    "POSITION_FORMAT_VERSION",
    "REPLAY_OPERATION_CONTRACT",
    "RESOURCE_FORMAT_VERSION",
    "STREAMING_CONTRACT_VERSION",
    "STREAMING_REGISTRY_REF",
    "AcknowledgementConflict",
    "ConsumerGroup",
    "Cursor",
    "CursorExpired",
    "Delivery",
    "DeliveryGuarantee",
    "DeliveryRejected",
    "DeliveryTimeout",
    "DeliveryToken",
    "Event",
    "EvidenceKind",
    "GroupPositionConflict",
    "GroupPositionTransition",
    "InvalidCursor",
    "InvalidEvent",
    "InvalidStreamingDefinition",
    "MigrationRequired",
    "OrderingGuarantee",
    "Position",
    "PublishReceipt",
    "RangePage",
    "RebalanceConflict",
    "ReplayOperation",
    "ResourceKind",
    "ResourcePolicy",
    "RetentionBoundaryExceeded",
    "Stream",
    "StreamingCapabilityMismatch",
    "StreamingCatalogProvider",
    "StreamingCatalogSurface",
    "StreamingDescriptor",
    "StreamingEvidence",
    "StreamingEvidenceHook",
    "StreamingHooks",
    "StreamingPolicyDenied",
    "StreamingPolicyHook",
    "StreamingResource",
    "StreamingResourceNotFound",
    "StreamingUnavailable",
    "Subscription",
    "__version__",
    "compatibility_contract",
    "contract_document",
    "negotiate_streaming_capabilities",
    "parse_resource",
    "public_api_contract",
    "require_streaming_capabilities",
    "resource_from_mapping",
    "streaming_manifest",
    "streaming_requirements",
    "validate_expression_arguments",
]
